name: "homeassistant-display"
description: "Display Home Assistant dashboards in kiosk mode directly on your HAOS server."
version: "1.0.4"
slug: "homeassistant-display"
arch:
  - aarch64
  - amd64
startup: application
host_network: true
init: false
ingress: true
homeassistant_api: true
auth_api: true
apparmor: false
udev: true
privileged:
  - SYS_ADMIN
  - NET_ADMIN
full_access: true

# Regroupement de tous les périphériques nécessaires
devices:
  - /dev/dri:/dev/dri
  - /dev/fb0:/dev/fb0
  - /dev/input:/dev/input
  - /dev/tty0:/dev/tty0

map:
  - addon_config:rw

options:
  ha_url: "http://127.0.0.1:8123"
  ha_dashboard: ""
  login_delay: 8.0
  zoom_level: 100
  browser_refresh: 600
  screen_timeout: 0
  output_number: 1
  dark_mode: true
  ha_sidebar: "none"
  rotate_display: "normal"
  map_touch_inputs: true
  cursor_timeout: 5
  keyboard_layout: us
  onscreen_keyboard_mode: "off"
  rest_port: 8080
  rest_bearer_token: ""
  debug_mode: false

schema:
  ha_username: str?
  ha_password: password?
  ha_url: str
  ha_dashboard: str?
  login_delay: float(0,)
  zoom_level: int(10,1000)
  browser_refresh: int(0,)
  screen_timeout: int(0,)
  output_number: int(1,2)
  dark_mode: bool
  ha_sidebar: list(full|narrow|none)
  rotate_display: list(normal|left|right|inverted)
  map_touch_inputs: bool
  cursor_timeout: int
  keyboard_layout: str
  onscreen_keyboard_mode: list(off|manual|always)
  rest_port: int(1024,49151)
  rest_bearer_token: password
  debug_mode: bool

environment:
  DISPLAY: ":0"
